---
- hosts: k8smaster
  gather_facts: false
  remote_user: mrg3admin
  tasks:  
    - block:
      - name: kubectl commands
        #remote_user: mrg3admin
        shell: kubectl get nodes;docker image ls
        register: out
      - debug: 
          var: out

      - debug: 
          var: out.stdout_lines

      - name: system command
        shell: hostname
        register: foo
      - debug: 
          var: foo
      become: yes
      become_user: mrg3admin 


